- name: Fix it now
  pattern: "[fF][iI][xX][mM][eE]"
  filePattern: ".*.py$"

- name: IPython debug leftover
  pattern: "IPython\\.embed()"
  filePattern: ".*.py$"

- name: Leftover print
  pattern: "print\\("
  filePattern: ^(?!.*conftest).*\.py$

- name: Use relative imports
  pattern: "import har2tavern|from har2tavern"
  filePattern: "src/.*.py$"
